<a href="https://colab.research.google.com/github/Geethanjali295/ML-PROJECT/blob/main/Day_2_ML_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
df=sns.load_dataset("titanic")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [5]:
df.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [6]:
df.shape

(891, 15)

In [7]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [9]:
df.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [10]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [11]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [12]:
df.drop(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[890 rows x 15 columns]

In [16]:
df=df.drop(columns=['deck'])
df.shape

(891, 14)

In [17]:
df.dropna(subset=['embarked','embark_town',],inplace=True)
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64


In [18]:
age_mean=df['age'].mean()
df['age']=df['age'].fillna(age_mean)

In [19]:
age_mean

np.float64(29.64209269662921)

In [22]:
df['age_group']=np.where(df['age']<18,"child","Adult")
df['age_group']

0      Adult
1      Adult
2      Adult
3      Adult
4      Adult
       ...  
886    Adult
887    Adult
888    Adult
889    Adult
890    Adult
Name: age_group, Length: 889, dtype: object

In [24]:
df['family_size']=df['sibsp']+df['parch']
df['family_size']

0      1
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    3
889    0
890    0
Name: family_size, Length: 889, dtype: int64

In [27]:
df['fare_per_person']=df['fare']/(df['family_size']+1)
df['fare_per_person']

0       3.62500
1      35.64165
2       7.92500
3      26.55000
4       8.05000
         ...   
886    13.00000
887    30.00000
888     5.86250
889    30.00000
890     7.75000
Name: fare_per_person, Length: 889, dtype: float64

In [28]:
df.rename(columns={'pclass':'Passenger_Class'},inplace=np.True_)
df

survived  Passenger_Class     sex        age  sibsp  parch     fare  \
0           0                3    male  22.000000      1      0   7.2500   
1           1                1  female  38.000000      1      0  71.2833   
2           1                3  female  26.000000      0      0   7.9250   
3           1                1  female  35.000000      1      0  53.1000   
4           0                3    male  35.000000      0      0   8.0500   
..        ...              ...     ...        ...    ...    ...      ...   
886         0                2    male  27.000000      0      0  13.0000   
887         1                1  female  19.000000      0      0  30.0000   
888         0                3  female  29.642093      1      2  23.4500   
889         1                1    male  26.000000      0      0  30.0000   
890         0                3    male  32.000000      0      0   7.7500   

    embarked   class    who  adult_male  embark_town alive  alone age_group  \
0          S   Third    man        True  Southampton    no  False     Adult   
1          C   First  woman       False    Cherbourg   yes  False     Adult   
2          S   Third  woman       False  Southampton   yes   True     Adult   
3          S   First  woman       False  Southampton   yes  False     Adult   
4          S   Third    man        True  Southampton    no   True     Adult   
..       ...     ...    ...         ...          ...   ...    ...       ...   
886        S  Second    man        True  Southampton    no   True     Adult   
887        S   First  woman       False  Southampton   yes   True     Adult   
888        S   Third  woman       False  Southampton    no  False     Adult   
889        C   First    man        True    Cherbourg   yes   True     Adult   
890        Q   Third    man        True   Queenstown    no   True     Adult   

     family_size  fare_per_person  
0              1          3.62500  
1              1         35.64165  
2              0          7.92500  
3              1         26.55000  
4              0          8.05000  
..           ...              ...  
886            0         13.00000  
887            0         30.00000  
888            3          5.86250  
889            0         30.00000  
890            0          7.75000  

[889 rows x 17 columns]

In [29]:
df[df['age']>df['age'].mean()]

survived  Passenger_Class     sex   age  sibsp  parch     fare embarked  \
1           1                1  female  38.0      1      0  71.2833        C   
3           1                1  female  35.0      1      0  53.1000        S   
4           0                3    male  35.0      0      0   8.0500        S   
6           0                1    male  54.0      0      0  51.8625        S   
11          1                1  female  58.0      0      0  26.5500        S   
..        ...              ...     ...   ...    ...    ...      ...      ...   
873         0                3    male  47.0      0      0   9.0000        S   
879         1                1  female  56.0      0      1  83.1583        C   
881         0                3    male  33.0      0      0   7.8958        S   
885         0                3  female  39.0      0      5  29.1250        Q   
890         0                3    male  32.0      0      0   7.7500        Q   

     class    who  adult_male  embark_town alive  alone age_group  \
1    First  woman       False    Cherbourg   yes  False     Adult   
3    First  woman       False  Southampton   yes  False     Adult   
4    Third    man        True  Southampton    no   True     Adult   
6    First    man        True  Southampton    no   True     Adult   
11   First  woman       False  Southampton   yes   True     Adult   
..     ...    ...         ...          ...   ...    ...       ...   
873  Third    man        True  Southampton    no   True     Adult   
879  First  woman       False    Cherbourg   yes  False     Adult   
881  Third    man        True  Southampton    no   True     Adult   
885  Third  woman       False   Queenstown    no  False     Adult   
890  Third    man        True   Queenstown    no   True     Adult   

     family_size  fare_per_person  
1              1        35.641650  
3              1        26.550000  
4              0         8.050000  
6              0        51.862500  
11             0        26.550000  
..           ...              ...  
873            0         9.000000  
879            1        41.579150  
881            0         7.895800  
885            5         4.854167  
890            0         7.750000  

[328 rows x 17 columns]

In [30]:
df[(df['sex']=='female') & (df['Passenger_Class']==1)]

survived  Passenger_Class     sex        age  sibsp  parch      fare  \
1           1                1  female  38.000000      1      0   71.2833   
3           1                1  female  35.000000      1      0   53.1000   
11          1                1  female  58.000000      0      0   26.5500   
31          1                1  female  29.642093      1      0  146.5208   
52          1                1  female  49.000000      1      0   76.7292   
..        ...              ...     ...        ...    ...    ...       ...   
856         1                1  female  45.000000      1      1  164.8667   
862         1                1  female  48.000000      0      0   25.9292   
871         1                1  female  47.000000      1      1   52.5542   
879         1                1  female  56.000000      0      1   83.1583   
887         1                1  female  19.000000      0      0   30.0000   

    embarked  class    who  adult_male  embark_town alive  alone age_group  \
1          C  First  woman       False    Cherbourg   yes  False     Adult   
3          S  First  woman       False  Southampton   yes  False     Adult   
11         S  First  woman       False  Southampton   yes   True     Adult   
31         C  First  woman       False    Cherbourg   yes  False     Adult   
52         C  First  woman       False    Cherbourg   yes  False     Adult   
..       ...    ...    ...         ...          ...   ...    ...       ...   
856        S  First  woman       False  Southampton   yes  False     Adult   
862        S  First  woman       False  Southampton   yes   True     Adult   
871        S  First  woman       False  Southampton   yes  False     Adult   
879        C  First  woman       False    Cherbourg   yes  False     Adult   
887        S  First  woman       False  Southampton   yes   True     Adult   

     family_size  fare_per_person  
1              1        35.641650  
3              1        26.550000  
11             0        26.550000  
31             1        73.260400  
52             1        38.364600  
..           ...              ...  
856            2        54.955567  
862            0        25.929200  
871            2        17.518067  
879            1        41.579150  
887            0        30.000000  

[92 rows x 17 columns]

In [31]:
df[(df['survived']==1)]

survived  Passenger_Class     sex   age  sibsp  parch     fare embarked  \
1           1                1  female  38.0      1      0  71.2833        C   
2           1                3  female  26.0      0      0   7.9250        S   
3           1                1  female  35.0      1      0  53.1000        S   
8           1                3  female  27.0      0      2  11.1333        S   
9           1                2  female  14.0      1      0  30.0708        C   
..        ...              ...     ...   ...    ...    ...      ...      ...   
875         1                3  female  15.0      0      0   7.2250        C   
879         1                1  female  56.0      0      1  83.1583        C   
880         1                2  female  25.0      0      1  26.0000        S   
887         1                1  female  19.0      0      0  30.0000        S   
889         1                1    male  26.0      0      0  30.0000        C   

      class    who  adult_male  embark_town alive  alone age_group  \
1     First  woman       False    Cherbourg   yes  False     Adult   
2     Third  woman       False  Southampton   yes   True     Adult   
3     First  woman       False  Southampton   yes  False     Adult   
8     Third  woman       False  Southampton   yes  False     Adult   
9    Second  child       False    Cherbourg   yes  False     child   
..      ...    ...         ...          ...   ...    ...       ...   
875   Third  child       False    Cherbourg   yes   True     child   
879   First  woman       False    Cherbourg   yes  False     Adult   
880  Second  woman       False  Southampton   yes  False     Adult   
887   First  woman       False  Southampton   yes   True     Adult   
889   First    man        True    Cherbourg   yes   True     Adult   

     family_size  fare_per_person  
1              1         35.64165  
2              0          7.92500  
3              1         26.55000  
8              2          3.71110  
9              1         15.03540  
..           ...              ...  
875            0          7.22500  
879            1         41.57915  
880            1         13.00000  
887            0         30.00000  
889            0         30.00000  

[340 rows x 17 columns]

In [32]:
df.groupby('sex')['survived'].mean()

sex
female    0.740385
male      0.188908
Name: survived, dtype: float64

In [34]:
df.groupby('class')['fare'].mean()

/tmp/ipython-input-4105422611.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('class')['fare'].mean()


class
First     84.193516
Second    20.662183
Third     13.675550
Name: fare, dtype: float64

In [35]:

df.corr(numeric_only=True)

survived  Passenger_Class       age     sibsp     parch  \
survived         1.000000        -0.335549 -0.074513 -0.034040  0.083151   
Passenger_Class -0.335549         1.000000 -0.328256  0.081656  0.016824   
age             -0.074513        -0.328256  1.000000 -0.231908 -0.178013   
sibsp           -0.034040         0.081656 -0.231908  1.000000  0.414542   
parch            0.083151         0.016824 -0.178013  0.414542  1.000000   
fare             0.255290        -0.548193  0.088780  0.160887  0.217532   
adult_male      -0.555520         0.090098  0.258793 -0.255401 -0.351945   
alone           -0.206207         0.138553  0.177445 -0.584186 -0.583112   
family_size      0.018277         0.064221 -0.247459  0.890654  0.782988   
fare_per_person  0.217902        -0.482024  0.136787 -0.093211 -0.067422   

                     fare  adult_male     alone  family_size  fare_per_person  
survived         0.255290   -0.555520 -0.206207     0.018277         0.217902  
Passenger_Class -0.548193    0.090098  0.138553     0.064221        -0.482024  
age              0.088780    0.258793  0.177445    -0.247459         0.136787  
sibsp            0.160887   -0.255401 -0.584186     0.890654        -0.093211  
parch            0.217532   -0.351945 -0.583112     0.782988        -0.067422  
fare             1.000000   -0.179851 -0.274079     0.218658         0.840902  
adult_male      -0.179851    1.000000  0.407992    -0.350419        -0.078503  
alone           -0.274079    0.407992  1.000000    -0.690654         0.042706  
family_size      0.218658   -0.350419 -0.690654     1.000000        -0.097399  
fare_per_person  0.840902   -0.078503  0.042706    -0.097399         1.000000

In [36]:
df=sns.load_dataset("tips")

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [38]:
df.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [39]:
df.shape  #244 rows

(244, 7)

In [40]:
df.size

1708

In [41]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [42]:
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [44]:
df_bill=df['total_bill'].mean()

In [45]:
df_bill

np.float64(19.78594262295082)

In [46]:
df_bill1=df['tip'].mean()
df_bill1

np.float64(2.99827868852459)

In [47]:
df['tip'].median()

2.9

In [50]:
df['Tip_percentage']=(df['tip']/df['total_bill'])*100
df

total_bill   tip     sex smoker   day    time  size  Tip_percentage
0         16.99  1.01  Female     No   Sun  Dinner     2        5.944673
1         10.34  1.66    Male     No   Sun  Dinner     3       16.054159
2         21.01  3.50    Male     No   Sun  Dinner     3       16.658734
3         23.68  3.31    Male     No   Sun  Dinner     2       13.978041
4         24.59  3.61  Female     No   Sun  Dinner     4       14.680765
..          ...   ...     ...    ...   ...     ...   ...             ...
239       29.03  5.92    Male     No   Sat  Dinner     3       20.392697
240       27.18  2.00  Female    Yes   Sat  Dinner     2        7.358352
241       22.67  2.00    Male    Yes   Sat  Dinner     2        8.822232
242       17.82  1.75    Male     No   Sat  Dinner     2        9.820426
243       18.78  3.00  Female     No  Thur  Dinner     2       15.974441

[244 rows x 8 columns]

In [61]:
df['high_spender']=np.where(df['total_bill']>df['total_bill'].mean(),"1","0")
df


total_bill   tip     sex smoker   day    time  size  Tip_percentage  \
0         16.99  1.01  Female     No   Sun  Dinner     2        5.944673   
1         10.34  1.66    Male     No   Sun  Dinner     3       16.054159   
2         21.01  3.50    Male     No   Sun  Dinner     3       16.658734   
3         23.68  3.31    Male     No   Sun  Dinner     2       13.978041   
4         24.59  3.61  Female     No   Sun  Dinner     4       14.680765   
..          ...   ...     ...    ...   ...     ...   ...             ...   
239       29.03  5.92    Male     No   Sat  Dinner     3       20.392697   
240       27.18  2.00  Female    Yes   Sat  Dinner     2        7.358352   
241       22.67  2.00    Male    Yes   Sat  Dinner     2        8.822232   
242       17.82  1.75    Male     No   Sat  Dinner     2        9.820426   
243       18.78  3.00  Female     No  Thur  Dinner     2       15.974441   

    high_spender  
0              0  
1              0  
2              1  
3              1  
4              1  
..           ...  
239            1  
240            1  
241            1  
242            0  
243            0  

[244 rows x 9 columns]

In [52]:
df['total_bill']>30

0      False
1      False
2      False
3      False
4      False
       ...  
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [53]:
df['Tip_percentage']>20

0      False
1      False
2      False
3      False
4      False
       ...  
239     True
240    False
241    False
242    False
243    False
Name: Tip_percentage, Length: 244, dtype: bool

In [57]:
df.groupby('sex')['tip'].mean()

/tmp/ipython-input-3407121299.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')['tip'].mean()


sex
Male      3.089618
Female    2.833448
Name: tip, dtype: float64

In [58]:
df.groupby('day')['total_bill'].mean()

/tmp/ipython-input-1881343769.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('day')['total_bill'].mean()


day
Thur    17.682742
Fri     17.151579
Sat     20.441379
Sun     21.410000
Name: total_bill, dtype: float64

In [59]:
df.groupby('smoker')['Tip_percentage'].mean()

/tmp/ipython-input-2619744683.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('smoker')['Tip_percentage'].mean()


smoker
Yes    16.319604
No     15.932846
Name: Tip_percentage, dtype: float64

In [62]:
df.corr(numeric_only=True)

total_bill       tip      size  Tip_percentage
total_bill        1.000000  0.675734  0.598315       -0.338624
tip               0.675734  1.000000  0.489299        0.342370
size              0.598315  0.489299  1.000000       -0.142860
Tip_percentage   -0.338624  0.342370 -0.142860        1.000000

In [64]:
#numpy
array=np.arange(1,17).reshape(4,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [67]:
y=np.arange(1,7)
y

array([1, 2, 3, 4, 5, 6])

In [69]:
y[y%2==0]=-1
y

array([ 1, -1,  3, -1,  5, -1])

In [70]:
arr1=np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

In [74]:
mean1=np.mean(arr1)
mean1

np.float64(30.0)

In [75]:
std1=np.std(arr1)
std1

np.float64(14.142135623730951)

In [78]:
normal1=(arr1-mean1)/std1
normal1

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [80]:
y1=np.array([1,2,3,
             4,5,6,
             7,8,9])
y1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
y1=np.arange(1,10).reshape(3,3)
y1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
y1[0][1]

np.int64(2)

In [85]:
y1[1][1]

np.int64(5)

In [86]:
y1[2][0]

np.int64(7)

In [87]:
y1[2]

array([7, 8, 9])

In [91]:
y1[1][1:]

array([5, 6])

In [98]:
y1[1:,:2]

array([[4, 5],
       [7, 8]])

In [101]:
y1[:2,1:]

array([[2, 3],
       [5, 6]])